// packages/cli/src/autopilot/pr-body.ts
//
// Title + body builder for night-shift auto-PRs. All free-text fields
// (root_cause, etc.) are passed through redactSecrets before any string
// reaches the PR body — secrets from raw_stdout MUST NOT leak to GitHub.

const SECRET_PATTERNS: Array<{ re: RegExp; label: string }> = [
  // OpenAI / Anthropic style API keys: sk-... with ≥ 20 chars
  { re: /sk-[A-Za-z0-9_-]{20,}/g, label: 'api-key' },
  // Bearer tokens
  { re: /Bearer\s+[A-Za-z0-9._\-+/=]+/g, label: 'bearer' },
  // password=... assignments (URL params, env-like)
  { re: /password=[^\s&;]+/gi, label: 'password' },
];

export function redactSecrets(input: string): string {
  let out = input;
  for (const { re, label } of SECRET_PATTERNS) {
    out = out.replace(re, `[REDACTED:${label}]`);
  }
  return out;
}

export interface BuildPrTitleInput {
  issueId: string;
  rootCause?: string;
}

export function buildPrTitle({ issueId, rootCause }: BuildPrTitleInput): string {
  const raw = rootCause?.trim();
  const summary = raw ? redactSecrets(raw).split(/[.!?\n]/)[0]!.slice(0, 79) : 'auto-fix';
  return `fix(contractqa): ${issueId} — ${summary}`;
}

export interface BuildPrBodyInput {
  issueId: string;
  rootCause?: string;
  filesChanged: string[];
  testsRun?: string[];
  regressionSummary: {
    httpPassed: number;
    skippedBrowserContracts: number;
    regressionContract?: string;
  };
  dashboardUrl?: string;
  runId?: string;
}

export function buildPrBody(i: BuildPrBodyInput): string {
  const lines: string[] = [];
  lines.push(`> Auto-generated by ContractQA night-shift auto-PR. Review carefully.`);
  lines.push('');
  lines.push(`**Issue ID:** \`${i.issueId}\``);
  lines.push('');

  lines.push('## Root cause');
  lines.push(i.rootCause ? redactSecrets(i.rootCause) : '_(none reported)_');
  lines.push('');

  lines.push('## Files changed');
  for (const f of i.filesChanged) lines.push(`- \`${f}\``);
  lines.push('');

  if (i.testsRun && i.testsRun.length > 0) {
    lines.push('## Tests run');
    for (const t of i.testsRun) lines.push(`- ${t}`);
    lines.push('');
  }

  lines.push('## Regression check');
  lines.push(`- ${i.regressionSummary.httpPassed} HTTP contracts passed`);
  if (i.regressionSummary.skippedBrowserContracts > 0) {
    lines.push(
      `- ⚠ ${i.regressionSummary.skippedBrowserContracts} browser contracts skipped ` +
        `(autopilot doesn't spin Playwright at fix-time — see spec §5.1)`,
    );
  }
  if (i.regressionSummary.regressionContract) {
    lines.push(`- ❌ REGRESSION detected: \`${i.regressionSummary.regressionContract}\``);
  }
  lines.push('');

  if (i.dashboardUrl && i.runId) {
    lines.push('## Dashboard');
    lines.push(`${i.dashboardUrl.replace(/\/$/, '')}/runs/${i.runId}`);
  }

  return lines.join('\n');
}
